import type { Campaign } from '@/lib/types';

export const sampleCampaign: Campaign = {
  slug: '7-wyvern-avenue-roseville',
  address: '7 Wyvern Avenue',
  suburb: 'Roseville',
  displayPrice: '$2.7m-$3.0m',
  campaignHeat: '6/10',
  daysOnMarket: 'TBC',
  contractsOut: 'TBC',
  heroImage: '/placeholder-hero.jpg',
  heroImages: [
    { kind: 'hero1', url: '/placeholder-hero.jpg', altText: 'Front exterior' },
    { kind: 'hero2', url: '/placeholder-hero.jpg', altText: 'Garden view' },
    { kind: 'hero3', url: '/placeholder-hero.jpg', altText: 'Living room' },
  ],
  propertyType: 'House',
  bedrooms: '3',
  bathrooms: '3',
  carSpaces: '2',
  landSize: '860sqm',
  goLiveDate: '',
  campaignMethod: 'Auction',
  advertisingCopy: 'Renovated family home with north-to-rear garden, flexible living zones, and strong indoor-outdoor flow.',
  notesInternal: '',
  mcgrathListingUrl: '',
  primaryAgents: [
    {
      role: 'lead',
      name: 'James Sutton',
      profileUrl: 'https://www.mcgrath.com.au/agents/james-sutton-a1V5g0000007PDMEA2',
      mobile: '',
      sortOrder: 0,
    },
    {
      role: 'second',
      name: 'Brie Dickson',
      profileUrl: 'https://www.mcgrath.com.au/agents/brie-dickson-a1VRE000000y4dR2AQ',
      mobile: '',
      sortOrder: 1,
    },
  ],
  supportAgent: {
    role: 'support',
    name: 'Ashley Coates',
    profileUrl: 'https://www.mcgrath.com.au/agents/ashley-coates-a1VRE000000yntt2AA',
    mobile: '',
    sortOrder: 0,
  },
  agentContactNotes: 'James Sutton | 04xx xxx xxx\nBrie Dickson | 04xx xxx xxx',
  compPrimarySuburb: 'Roseville',
  compNearbySuburbs: 'Lindfield, Killara, Gordon',
  compBedroomRule: '3 bed only',
  compBathroomRule: '',
  compCarRule: '',
  compPriceBandPct: '10',
  compPropertyTypeRule: 'Similar family-home product',
  compNotes: '',
  projectionHeadline: '',
  recommendedStrategyLabel: '',
  recommendedStrategyBody: '',
  marketConditions: '',
};
